# ./worker/pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "worker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "db-service",  # Linked workspace dependency
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.0",
    "langchain-nvidia-ai-endpoints",
    "langchain-tavily",
    "langgraph>=1.2.9",
    "pydantic>=2.13.4",
    "python-dotenv",
]

[tool.setuptools.packages.find]
include = ["worker*"]

[tool.uv.sources]
db-service = { workspace = true }
